### ISSUE TITLE
Error loading LTX-Video nodes in ComfyUI

### ISSUE THREAD

**Issue by Tachyon1986** [Lightricks/ComfyUI-LTXVideo#10]
ComfyUI Manager is unable to load the ltx-video module. I already cloned and installed it manually (pip install requirements.txt):
![image](https://github.com/user-attachments/assets/41582251-60b0-429e-90b0-8902277a13e5)

![image](https://github.com/user-attachments/assets/89b558c0-88af-4b81-b1b6-0dfd28f1bc84)

`Total VRAM 10240 MB, total RAM 32712 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI_windows_portable\ComfyUI\web
D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[Impact Pack] Wildcards loading done.
Initializing EasyNodes. Auto-registration: True
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\__init__.py", line 3, in <module>
    from .transformer import LTXVModelConfigurator, LTXVShiftSigmas
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\transformer.py", line 15, in <module>
    from ltx_video.models.transformers.transformer3d import Transformer3DModel
ModuleNotFoundError: No module named 'ltx_video'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo module for custom nodes: No module named 'ltx_video'`

**Comment by Tachyon1986** [comment]
I forgot to add this . There's an error when installing ComfyUI-LTX video
` Collecting sentencepiece~=0.1.96 (from ltx-video@ git+https://github.com/Lightricks/LTX-Video.git@ltx-video-0.9)
   Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'done'
   Getting requirements to build wheel: started
   Getting requirements to build wheel: finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Getting requirements to build wheel did not run successfully.
[!]   exit code: 1
[!]
[!]   [24 lines of output]
[!]   Traceback (most recent call last):
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
[!]       main()
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
[!]       json_out['return_val'] = hook(**hook_input['kwargs'])
[!]                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
[!]       return hook(config_settings)
[!]              ^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
[!]       return self._get_build_requires(config_settings, requirements=[])
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 303, in _get_build_requires
[!]       self.run_setup()
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 521, in run_setup
[!]       super().run_setup(setup_script=setup_script)
[!]     File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\build_meta.py", line 319, in run_setup
[!]       exec(code, locals())
[!]     File "<string>", line 126, in <module>
[!]     File "subprocess.py", line 408, in check_call
[!]     File "subprocess.py", line 389, in call
[!]     File "subprocess.py", line 1026, in __init__
[!]     File "subprocess.py", line 1538, in _execute_child
[!]   FileNotFoundError: [WinError 2] The system cannot find the file specified
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!] error: subprocess-exited-with-error
[!]
[!] Getting requirements to build wheel did not run successfully.
[!] exit code: 1
[!]
[!] See above for output.
[!]
[!] note: This error originates from a subprocess, and is likely not a problem with pip.
install/(de)activation script failed: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo`

**Comment by Lumabrik** [comment]
There seems to be an issue with the LTX nodes working with the portable version of Comfy. One of the LTX team on Discord mentioned they are aware of it and hopefully it will be fixed soon.

**Comment by Musigreg** [comment]
> There seems to be an issue with the LTX nodes working with the portable version of Comfy. One of the LTX team on Discord mentioned they are aware of it and hopefully it will be fixed soon. I have the same issue.
> 
> Currently these native workflows do work with comfy ....
> 
> https://comfyanonymous.github.io/ComfyUI_examples/ltxv/

Thank you very much for the link! Works like a charm! Waiting for the fix, though.

**Comment by kvochko** [comment]
@Tachyon1986 this should be fixed now, please let us know if you still have any issues installing the nodes

**Comment by Musigreg** [comment]
> @Tachyon1986 this should be fixed now, please let us know if you still have any issues installing the nodes

The install works and the missing nodes are not missing anymore. I can't use text-encoders, though. Wrong path or model error.
Do you have to use your encoder? Pixart-XL?

**Comment by kvochko** [comment]
It’s not strictly necessary, you can use [t5xxl_fp16.safetensors](https://huggingface.co/Comfy-Org/mochi_preview_repackaged/blob/main/split_files/text_encoders/t5xxl_fp16.safetensors) with the built-in clip loader node (see #15  for example), although the results might differ.

**Comment by Musigreg** [comment]
Gotcha. Thank you. 
I have other errors with Mat1 Mat2, etc... But I'm fixing it.

At least this particular issue (Nodes missing) is solved.

**Comment by vu0tran** [comment]
<img width="580" alt="Screenshot 2024-11-23 at 12 06 34 PM" src="https://github.com/user-attachments/assets/f30f5d28-8455-4679-9010-8009024fbc3c">

I'm missing the LTXV CLIP Model Loader even though I've installed the LTXV Custom node through manager. Any idea what's happening?

**Comment by Musigreg** [comment]
Did you try uninstalling and reinstalling it completely?

**Comment by vu0tran** [comment]
> Did you try uninstalling and reinstalling it completely?

Yes. I tried to uninstall the [ComfyUI-LTXVideo](https://github.com/Lightricks/ComfyUI-LTXVideo) library and reinstalled and restarted

**Comment by vu0tran** [comment]
I even tried to rm -rf and did a manual install

**Comment by vu0tran** [comment]
I got it resolved. For those having similar issues, it was due to me not upgrading my ComfyUI. There's a missing enum to the text_encoders folder. Thank you!

**Comment by Tapyon** [comment]
> I got it resolved. For those having similar issues, it was due to me not upgrading my ComfyUI. There's a missing enum to the text_encoders folder. Thank you!

what means this ?? 
its february and i have the same issue, with just those specfic nodes !
something got fixed on this matteR?

**Comment by BenDes21** [comment]
this issue is still no fixed after 1 year -_-
