### ISSUE TITLE
[!] ltx-video 0.1.0 requires diffusers~=0.28.2, but you have diffusers 0.31.0 which is incompatible.

### ISSUE THREAD

**Issue by zejacky** [Lightricks/ComfyUI-LTXVideo#16]
First, I like to say thank you for this amazing project. I got a video rendered, with the example node, in 44 secs! (4090)

The "error" I mentioned occurred, after the initial installation of the LTXVideo node. 
CogVideoXWrapper and PyramidFlow custom node failed to load. After I did a "Try fix", reinstall of CogVideoXWrapper, which installed diffusers 0.31.0.  The nodes start to work again.
However, LTXVideo looks like its working fine with diffusers 0.31.0.

**Comment by BigBlueGX** [comment]
Yes I had the same issue
