### ISSUE TITLE
MESSAGE ERROR : LTXVLoader Allocation on device

### ISSUE THREAD

**Issue by ABIA2024** [Lightricks/ComfyUI-LTXVideo#26]
the LOG : 
2024-11-24T09:53:04.492094 - Got an OOM, unloading all loaded models.
2024-11-24T09:53:04.493094 - Prompt executed in 86.73 seconds
2024-11-24T10:14:14.830664 - got prompt
2024-11-24T10:14:34.073877 - !!! Exception during processing !!! Allocation on device 
2024-11-24T10:14:34.074851 - Traceback (most recent call last):
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\loader_node.py", line 53, in load
    model = self._load_unet(
            ^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\loader_node.py", line 138, in _load_unet
    transformer.to(torch.float32).to(load_device).eval()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "D:\PINOKIO2\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
           ^^^^^
torch.OutOfMemoryError: Allocation on device 

2024-11-24T10:14:34.075877 - Got an OOM, unloading all loaded models.
2024-11-24T10:14:34.076883 - Prompt executed in 19.23 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":18,"nodes":[{"id":1,"type":"SamplerCustomAdvanced","pos":[-1477.5946044921875,1005.5457153320312],"size":[355.20001220703125,106],"flags":{},"order":11,"mode":0,"inputs":[{"name":"noise","type":"NOISE","link":3},{"name":"guider","type":"GUIDER","link":9},{"name":"sampler","type":"SAMPLER","link":5},{"name":"sigmas","type":"SIGMAS","link":6},{"name":"latent_image","type":"LATENT","link":12}],"outputs":[{"name":"output","type":"LATENT","links":[1],"slot_index":0},{"name":"denoised_output","type":"LATENT","links":null}],"properties":{"Node name for S&R":"SamplerCustomAdvanced"},"widgets_values":[]},{"id":2,"type":"VAEDecode","pos":[-1054.102783203125,1020.0283813476562],"size":[210,46],"flags":{},"order":12,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":1},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":3,"type":"VHS_VideoCombine","pos":[-804.1972045898438,1000.3211059570312],"size":[215,238],"flags":{},"order":13,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":2},{"name":"audio","type":"AUDIO","link":null,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":24,"loop_count":0,"filename_prefix":"AnimateDiff","format":"video/h264-mp4","pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{},"muted":false}}},{"id":4,"type":"RandomNoise","pos":[-1864,739],"size":[315,82],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"NOISE","type":"NOISE","links":[3]}],"properties":{"Node name for S&R":"RandomNoise"},"widgets_values":[176020827657638,"randomize"]},{"id":6,"type":"KSamplerSelect","pos":[-1877,1061],"size":[315,58],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"SAMPLER","type":"SAMPLER","links":[5]}],"properties":{"Node name for S&R":"KSamplerSelect"},"widgets_values":["euler"]},{"id":7,"type":"LTXVShiftSigmas","pos":[-1875,1181],"size":[315,106],"flags":{},"order":10,"mode":0,"inputs":[{"name":"sigmas","type":"SIGMAS","link":7},{"name":"sigma_shift","type":"FLOAT","link":11,"widget":{"name":"sigma_shift"}}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[6]}],"properties":{"Node name for S&R":"LTXVShiftSigmas"},"widgets_values":[1.820833333,true,0.1]},{"id":8,"type":"BasicScheduler","pos":[-2346,604],"size":[315,106],"flags":{},"order":8,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":8}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[7]}],"properties":{"Node name for S&R":"BasicScheduler"},"widgets_values":["normal",20,1]},{"id":9,"type":"LTXVModelConfigurator","pos":[-2822,667],"size":[378,242],"flags":{},"order":4,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":17},{"name":"vae","type":"VAE","link":null},{"name":"conditioning","type":"IMAGE","link":null,"shape":7}],"outputs":[{"name":"model","type":"MODEL","links":[8,10],"slot_index":0},{"name":"latent","type":"LATENT","links":[12],"slot_index":1},{"name":"sigma_shift","type":"FLOAT","links":[11],"slot_index":2}],"properties":{"Node name for S&R":"LTXVModelConfigurator"},"widgets_values":["Custom",1200,720,105,25,1,true]},{"id":10,"type":"CFGGuider","pos":[-1858,894],"size":[315,98],"flags":{},"order":9,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":10},{"name":"positive","type":"CONDITIONING","link":13},{"name":"negative","type":"CONDITIONING","link":14}],"outputs":[{"name":"GUIDER","type":"GUIDER","links":[9]}],"properties":{"Node name for S&R":"CFGGuider"},"widgets_values":[4]},{"id":11,"type":"CLIPTextEncode","pos":[-2828,953],"size":[400,200],"flags":{},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":15}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[13]}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["a vibrant field of flowers under a blue sky whit bright sunlight streaming through"]},{"id":12,"type":"CLIPTextEncode","pos":[-2823,1197],"size":[400,200],"flags":{},"order":7,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":16}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[14]}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["worst quality, inconsistent motion, blurry, kittery, distorded, watermarks "]},{"id":14,"type":"LTXVLoader","pos":[-3309,715],"size":[315,78],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"model","type":"MODEL","links":[17]},{"name":"vae","type":"VAE","links":[18],"slot_index":1}],"properties":{"Node name for S&R":"LTXVLoader"},"widgets_values":["ltx-video-2b-v0.9.safetensors"]},{"id":15,"type":"Anything Everywhere","pos":[-3197,860],"size":[239.40000915527344,26],"flags":{"collapsed":true},"order":5,"mode":0,"inputs":[{"name":"VAE","type":"*","link":18,"shape":7,"color_on":"#FF6E6E"}],"outputs":[],"properties":{"Node name for S&R":"Anything Everywhere","group_restricted":0,"color_restricted":0},"widgets_values":[]},{"id":13,"type":"LTXVCLIPModelLoader","pos":[-3444,951],"size":[467.08624267578125,60.697113037109375],"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"clip","type":"CLIP","links":[15,16],"slot_index":0}],"properties":{"Node name for S&R":"LTXVCLIPModelLoader"},"widgets_values":["PixArt-XL-2-1024-MS\\text_encoder\\model-00001-of-00002.safetensors"]}],"links":[[1,1,0,2,0,"LATENT"],[2,2,0,3,0,"IMAGE"],[3,4,0,1,0,"NOISE"],[5,6,0,1,2,"SAMPLER"],[6,7,0,1,3,"SIGMAS"],[7,8,0,7,0,"SIGMAS"],[8,9,0,8,0,"MODEL"],[9,10,0,1,1,"GUIDER"],[10,9,0,10,0,"MODEL"],[11,9,2,7,1,"FLOAT"],[12,9,1,1,4,"LATENT"],[13,11,0,10,1,"CONDITIONING"],[14,12,0,10,2,"CONDITIONING"],[15,13,0,11,0,"CLIP"],[16,13,0,12,0,"CLIP"],[17,14,0,9,0,"MODEL"],[18,14,1,15,0,"VAE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.5983178688116698,"offset":[3812.674407896231,-355.03454644570087]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
  

my question: is it possible to turn this custom node with 8Go VBRAM ?

**Comment by jgardet** [comment]
I have the same issue with an RTX4080

**Comment by jirachi155** [comment]
I'm on Quadro RTX 6000 with 40GB of RAM and 24GB VRAM, so I feel the issue is more on the software side? I even tried running with --lowvram param, but same issue.

### System Information
**OS:** nt
**Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct 1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
**Embedded Python:** true
**Pytorch Version:** 2.5.1+cu124
**Arguments:** ComfyUI\main.py --windows-standalone-build --cuda-malloc --lowvram
**RAM Total:** 40.98 GB
**RAM Free:** 16.46 GB

### Devices
**Type:** cuda
**VRAM Total:** 24 GB
**VRAM Free:** 21.94 GB
**Torch VRAM Total:** 928 MB
**Torch VRAM Free:** 120.27 MB

**Comment by kvochko** [comment]
@ABIA2024 Thanks! We added a dtype selector to the loader node, try loading the node in fp16. If you still have issues with VRAM, try lowering the resolution of frame count. Feel free to open another issue if you still have problems.

**Comment by ABIA2024** [comment]
ok, thanks , just a doubt: i have to load loader_node.nl
 like  loader_node.nl or rename it with the extension.py like loader_node.py ? 
I ask that because i see only file *.py in the folder ..\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo

**Comment by jgardet** [comment]
It hasn't fixed the issue for me

**Comment by ABIA2024** [comment]
I have insert the file loader_node.py in the folder \ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo and i get the same result:  LTXVLoader Allocation on device ...

**Comment by APCOTech** [comment]
> @ABIA2024 Thanks! We added a dtype selector to the loader node, try loading the model in fp16. If you still have issues with VRAM, try lowering the resolution or frame count. Feel free to open another issue if you still have problems.

Hi, I do not think it is about the resolution of frame count.. it can't pass the model loader node.

**Comment by j2l** [comment]
I have the same problem with latest version (installed today). 
I can load the model using internal "Load Checkpoint" so it's not a hardware issue.
