### ISSUE TITLE
Fail to build the wheel

### ISSUE THREAD

**Issue by scofano** [Lightricks/ComfyUI-LTXVideo#4]
Brand new Comfyui portable installation:

Building wheels for collected packages: ltx-video, sentencepiece
   Building wheel for ltx-video (pyproject.toml): started
   Building wheel for ltx-video (pyproject.toml): finished with status 'done'
   Created wheel for ltx-video: filename=ltx_video-0.1.0-py3-none-any.whl size=73380 sha256=a07f6e5c292005e793015d30cc797ea3f05f440812d11df00f304d3d4e32b3c0
   Stored in directory: C:\Users\Admin\AppData\Local\Temp\pip-ephem-wheel-cache-z26dehxa\wheels\60\be\53\ee2e5c8efdcc19dbdf6076dedefa22542ea5c34c90017dcf9f
   Building wheel for sentencepiece (pyproject.toml): started
   Building wheel for sentencepiece (pyproject.toml): finished with status 'error'
[!]   error: subprocess-exited-with-error
[!]
[!]   Building wheel for sentencepiece (pyproject.toml) did not run successfully.
[!]   exit code: 1
[!]
[!]   [63 lines of output]
[!]   CMake Deprecation Warning at CMakeLists.txt:15 (cmake_minimum_required):
[!]     Compatibility with CMake < 3.5 will be removed from a future version of
[!]     CMake.
[!]
[!]     Update the VERSION argument <min> value or use a ...<max> suffix to tell
[!]     CMake that the project does not need compatibility with older versions.
[!]
[!]
[!]   -- VERSION: 0.1.99
[!]   -- Selecting Windows SDK version 10.0.26100.0 to target Windows 10.0.22631.
[!]   -- Not Found TCMalloc: TCMALLOC_LIB-NOTFOUND
[!]   -- Configuring done (0.0s)
[!]   -- Generating done (0.2s)
[!]   -- Build files have been written to: C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/build
[!]   VersÃ£o do MSBuild 17.12.6+db5f6012c para .NET Framework
[!]
[!]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: O diretÃ³rio IntermediÃ¡rio ou o diretÃ³rio de SaÃ­da nÃ£o podem residir sob o diretÃ³rio TemporÃ¡rio porque isso poderia levar a problemas com a compilaÃ§Ã£o incremental. [C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\ZERO_CHECK.vcxproj]
[!]     1>Checking Build System
[!]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: O diretÃ³rio IntermediÃ¡rio ou o diretÃ³rio de SaÃ­da nÃ£o podem residir sob o diretÃ³rio TemporÃ¡rio porque isso poderia levar a problemas com a compilaÃ§Ã£o incremental. [C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\sentencepiece_train-static.vcxproj]
[!]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: O diretÃ³rio IntermediÃ¡rio ou o diretÃ³rio de SaÃ­da nÃ£o podem residir sob o diretÃ³rio TemporÃ¡rio porque isso poderia levar a problemas com a compilaÃ§Ã£o incremental. [C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\sentencepiece-static.vcxproj]
[!]     sentencepiece-static.vcxproj -> C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\Release\sentencepiece.lib
[!]     sentencepiece_train-static.vcxproj -> C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\Release\sentencepiece_train.lib
[!]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: O diretÃ³rio IntermediÃ¡rio ou o diretÃ³rio de SaÃ­da nÃ£o podem residir sob o diretÃ³rio TemporÃ¡rio porque isso poderia levar a problemas com a compilaÃ§Ã£o incremental. [C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\spm_export_vocab.vcxproj]
[!]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: O diretÃ³rio IntermediÃ¡rio ou o diretÃ³rio de SaÃ­da nÃ£o podem residir sob o diretÃ³rio TemporÃ¡rio porque isso poderia levar a problemas com a compilaÃ§Ã£o incremental. [C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\spm_encode.vcxproj]
[!]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: O diretÃ³rio IntermediÃ¡rio ou o diretÃ³rio de SaÃ­da nÃ£o podem residir sob o diretÃ³rio TemporÃ¡rio porque isso poderia levar a problemas com a compilaÃ§Ã£o incremental. [C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\spm_train.vcxproj]
[!]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: O diretÃ³rio IntermediÃ¡rio ou o diretÃ³rio de SaÃ­da nÃ£o podem residir sob o diretÃ³rio TemporÃ¡rio porque isso poderia levar a problemas com a compilaÃ§Ã£o incremental. [C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\spm_normalize.vcxproj]
[!]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: O diretÃ³rio IntermediÃ¡rio ou o diretÃ³rio de SaÃ­da nÃ£o podem residir sob o diretÃ³rio TemporÃ¡rio porque isso poderia levar a problemas com a compilaÃ§Ã£o incremental. [C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\spm_decode.vcxproj]
[!]     spm_normalize.vcxproj -> C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\Release\spm_normalize.exe
[!]     spm_encode.vcxproj -> C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\Release\spm_encode.exe
[!]     spm_decode.vcxproj -> C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\Release\spm_decode.exe
[!]     spm_train.vcxproj -> C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\Release\spm_train.exe
[!]     spm_export_vocab.vcxproj -> C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\src\Release\spm_export_vocab.exe
[!]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: O diretÃ³rio IntermediÃ¡rio ou o diretÃ³rio de SaÃ­da nÃ£o podem residir sob o diretÃ³rio TemporÃ¡rio porque isso poderia levar a problemas com a compilaÃ§Ã£o incremental. [C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\ALL_BUILD.vcxproj]
[!]     Building Custom Rule C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/sentencepiece/CMakeLists.txt
[!]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: O diretÃ³rio IntermediÃ¡rio ou o diretÃ³rio de SaÃ­da nÃ£o podem residir sob o diretÃ³rio TemporÃ¡rio porque isso poderia levar a problemas com a compilaÃ§Ã£o incremental. [C:\Users\Admin\AppData\Local\Temp\pip-install-zevzvfpv\sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d\build\install.vcxproj]
[!]     1>
[!]      -- Install configuration: "Release"
Successfully built ltx-video
[!]      -- Up-to-date: C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/build/root/lib/sentencepiece.lib
Failed to build sentencepiece
[!]     -- Up-to-date: C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/build/root/lib/sentencepiece_train.lib
[!]     -- Up-to-date: C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/build/root/bin/spm_encode.exe
[!]     -- Up-to-date: C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/build/root/bin/spm_decode.exe
[!]     -- Up-to-date: C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/build/root/bin/spm_normalize.exe
[!]     -- Up-to-date: C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/build/root/bin/spm_train.exe
[!]     -- Up-to-date: C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/build/root/bin/spm_export_vocab.exe
[!]     -- Up-to-date: C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/build/root/include/sentencepiece_trainer.h
[!]     -- Up-to-date: C:/Users/Admin/AppData/Local/Temp/pip-install-zevzvfpv/sentencepiece_3e26222a4dd04fbaad4683ffc2d2682d/build/root/include/sentencepiece_processor.h
[!]   D:\ComfyUI_VIDEO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
[!]     warnings.warn(msg)
[!]   running bdist_wheel
[!]   running build
[!]   running build_py
[!]   creating build\lib.win-amd64-cpython-312\sentencepiece
[!]   copying src\sentencepiece/__init__.py -> build\lib.win-amd64-cpython-312\sentencepiece
[!]   copying src\sentencepiece/_version.py -> build\lib.win-amd64-cpython-312\sentencepiece
[!]   copying src\sentencepiece/sentencepiece_model_pb2.py -> build\lib.win-amd64-cpython-312\sentencepiece
[!]   copying src\sentencepiece/sentencepiece_pb2.py -> build\lib.win-amd64-cpython-312\sentencepiece
[!]   running build_ext
[!]   building 'sentencepiece._sentencepiece' extension
[!]   creating build\temp.win-amd64-cpython-312\Release\src\sentencepiece
[!]   "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -ID:\ComfyUI_VIDEO\ComfyUI_windows_portable\python_embeded\include -ID:\ComfyUI_VIDEO\ComfyUI_windows_portable\python_embeded\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" /EHsc /Tpsrc/sentencepiece/sentencepiece_wrap.cxx /Fobuild\temp.win-amd64-cpython-312\Release\src/sentencepiece/sentencepiece_wrap.obj /std:c++17 /I.\build\root\include
[!]   sentencepiece_wrap.cxx
[!]   src/sentencepiece/sentencepiece_wrap.cxx(178): fatal error C1083: NÆo ‚ poss¡vel abrir arquivo incluir: 'Python.h': No such file or directory
[!]   error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
[!]   [end of output]
[!]
[!]   note: This error originates from a subprocess, and is likely not a problem with pip.
[!]   ERROR: Failed building wheel for sentencepiece
[!] ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (sentencepiece)
install/(de)activation script failed: D:\ComfyUI_VIDEO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo

**Comment by al3dv2** [comment]
Same

**Comment by kvochko** [comment]
Hi @scofano! Could you please attach the output of `pip list` here?

**Comment by scofano** [comment]
@kvochko 

Sure!

PS D:\ComfyUI_VIDEO> python_embeded\python.exe -m pip list
Package                                 Version
--------------------------------------- ------------
accelerate                              1.1.1
aiohappyeyeballs                        2.4.3
aiohttp                                 3.11.7
aiosignal                               1.3.1
altair                                  5.4.1
annotated-types                         0.7.0
ansi2html                               1.9.2
anyio                                   4.6.2.post1
arxiv                                   2.1.3
attrs                                   24.2.0
audioread                               3.0.1
beautifulsoup4                          4.12.3
bitsandbytes                            0.44.1
blinker                                 1.9.0
cachetools                              5.5.0
certifi                                 2024.8.30
cffi                                    1.17.1
charset-normalizer                      3.4.0
click                                   8.1.7
cmake                                   3.31.0.1
color-matcher                           0.5.0
colorama                                0.4.6
coloredlogs                             15.0.1
ComfyUI-EasyNodes                       1.2.7
contourpy                               1.3.1
cpm-kernels                             1.0.11
cryptography                            43.0.3
cstr                                    0.1.0
cycler                                  0.12.1
dataclasses-json                        0.6.7
datasets                                3.1.0
ddt                                     1.7.2
decorator                               5.1.1
Deprecated                              1.2.15
dill                                    0.3.8
dirtyjson                               1.0.8
diskcache                               5.6.3
distlib                                 0.3.9
distro                                  1.9.0
docutils                                0.21.2
docx2txt                                0.8
easyocr                                 1.7.2
einops                                  0.8.0
et_xmlfile                              2.0.0
fairscale                               0.4.13
faiss-cpu                               1.9.0.post1
fastapi                                 0.115.5
feedparser                              6.0.11
ffmpeg-python                           0.2.0
ffmpy                                   0.3.0
filelock                                3.16.1
filetype                                1.2.0
flatbuffers                             24.3.25
fonttools                               4.55.0
frozenlist                              1.5.0
fsspec                                  2024.9.0
future                                  1.0.0
gitdb                                   4.0.11
GitPython                               3.1.43
google-ai-generativelanguage            0.6.10
google-api-core                         2.23.0
google-api-python-client                2.154.0
google-auth                             2.36.0
google-auth-httplib2                    0.2.0
google-generativeai                     0.8.3
googleapis-common-protos                1.66.0
greenlet                                3.1.1
grpcio                                  1.68.0
grpcio-status                           1.68.0
h11                                     0.14.0
html2image                              2.0.5
html5lib                                1.1
httpcore                                1.0.7
httplib2                                0.22.0
httpx                                   0.27.2
httpx-sse                               0.4.0
huggingface-hub                         0.25.2
humanfriendly                           10.0
idna                                    3.10
imageio                                 2.36.0
imageio-ffmpeg                          0.5.1
img2texture                             1.0.6
Jinja2                                  3.1.4
jiter                                   0.7.1
joblib                                  1.4.2
json_repair                             0.30.2
jsonpatch                               1.33
jsonpointer                             3.0.0
jsonschema                              4.23.0
jsonschema-specifications               2024.10.1
keyboard                                0.13.5
kiwisolver                              1.4.7
kornia                                  0.7.4
kornia_rs                               0.1.7
langchain                               0.3.7
langchain-community                     0.3.7
langchain-core                          0.3.19
langchain-openai                        0.2.9
langchain-text-splitters                0.3.2
langsmith                               0.1.144
latex2mathml                            3.77.0
lazy_loader                             0.4
librosa                                 0.10.2.post1
llama-cloud                             0.1.5
llama_cpp_python                        0.2.90
llama-index                             0.12.1
llama-index-agent-openai                0.4.0
llama-index-cli                         0.4.0
llama-index-core                        0.12.1
llama-index-embeddings-openai           0.3.0
llama-index-indices-managed-llama-cloud 0.6.2
llama-index-legacy                      0.9.48.post4
llama-index-llms-openai                 0.3.1
llama-index-multi-modal-llms-openai     0.3.0
llama-index-program-openai              0.3.0
llama-index-question-gen-openai         0.3.0
llama-index-readers-file                0.4.0
llama-index-readers-llama-parse         0.4.0
llama-parse                             0.5.15
llvmlite                                0.43.0
Markdown                                3.7
markdown-it-py                          3.0.0
markdownify                             0.13.1
MarkupSafe                              3.0.2
marshmallow                             3.23.1
matplotlib                              3.9.2
matrix-client                           0.4.0
mdtex2html                              1.3.0
mdurl                                   0.1.2
moviepy                                 2.0.0
mpmath                                  1.3.0
msgpack                                 1.1.0
mss                                     10.0.0
multidict                               6.1.0
multiprocess                            0.70.16
mypy-extensions                         1.0.0
narwhals                                1.14.1
neo4j                                   5.26.0
nest-asyncio                            1.6.0
networkx                                3.4.2
ninja                                   1.11.1.1
nltk                                    3.9.1
numba                                   0.60.0
numpy                                   1.26.4
onnxruntime                             1.20.1
openai                                  1.55.0
opencv-python                           4.10.0.84
opencv-python-headless                  4.10.0.84
openpyxl                                3.1.5
optimum                                 1.23.3
orjson                                  3.10.11
outcome                                 1.3.0.post0
packaging                               24.2
pandas                                  2.2.3
pdfminer.six                            20231228
pdfplumber                              0.11.4
peft                                    0.13.2
piexif                                  1.1.3
pilgram                                 1.2.1
pillow                                  10.4.0
pip                                     24.3.1
platformdirs                            4.3.6
pooch                                   1.8.2
proglog                                 0.1.10
propcache                               0.2.0
proto-plus                              1.25.0
protobuf                                5.28.3
psutil                                  6.1.0
py-cord                                 2.6.1
py-cpuinfo                              9.0.0
pyarrow                                 18.0.0
pyasn1                                  0.6.1
pyasn1_modules                          0.4.1
pyclipper                               1.3.0.post6
pycparser                               2.22
pydantic                                2.9.2
pydantic_core                           2.23.4
pydantic-settings                       2.6.1
pydeck                                  0.9.1
pydub                                   0.25.1
pygit2                                  1.16.0
PyGithub                                2.5.0
Pygments                                2.18.0
PyJWT                                   2.10.0
PyMatting                               1.1.13
PyNaCl                                  1.5.0
pyparsing                               3.2.0
pypdf                                   5.1.0
pypdfium2                               4.30.0
pyreadline3                             3.5.4
PySocks                                 1.7.1
python-bidi                             0.6.3
python-dateutil                         2.9.0.post0
python-dotenv                           1.0.1
pytz                                    2024.2
PyYAML                                  6.0.2
referencing                             0.35.1
regex                                   2024.11.6
rembg                                   2.0.60
requests                                2.32.3
requests-toolbelt                       1.0.0
rich                                    13.9.4
rpds-py                                 0.21.0
rsa                                     4.9
safetensors                             0.4.5
scikit-image                            0.24.0
scikit-learn                            1.5.2
scipy                                   1.14.1
seaborn                                 0.13.2
segment-anything                        1.0
selenium                                4.26.1
Send2Trash                              1.8.3
sentence-transformers                   3.3.1
sentencepiece                           0.2.0
setuptools                              75.6.0
sgmllib3k                               1.0.0
shapely                                 2.0.6
shellingham                             1.5.4
six                                     1.16.0
smmap                                   5.0.1
sniffio                                 1.3.1
sortedcontainers                        2.4.0
sounddevice                             0.5.1
soundfile                               0.12.1
soupsieve                               2.6
soxr                                    0.5.0.post1
spandrel                                0.4.0
SQLAlchemy                              2.0.35
srt                                     3.5.3
starlette                               0.41.3
streamlit                               1.40.1
striprtf                                0.0.26
sympy                                   1.13.1
tabulate                                0.9.0
tenacity                                8.5.0
threadpoolctl                           3.5.0
tifffile                                2024.9.20
tiktoken                                0.8.0
timm                                    1.0.11
tokenizers                              0.20.3
toml                                    0.10.2
torch                                   2.5.1+cu124
torchaudio                              2.5.1+cu124
torchsde                                0.2.6
torchvision                             0.20.1+cu124
tornado                                 6.4.2
tqdm                                    4.67.0
trampoline                              0.1.2
transformers                            4.46.3
transformers-stream-generator           0.0.5
trio                                    0.27.0
trio-websocket                          0.11.1
typer                                   0.13.1
typing_extensions                       4.12.2
typing-inspect                          0.9.0
tzdata                                  2024.2
ultralytics                             8.3.36
ultralytics-thop                        2.0.12
uritemplate                             4.1.1
urllib3                                 1.26.20
uvicorn                                 0.32.1
verovio                                 4.3.1
virtualenv                              20.27.1
watchdog                                6.0.0
webencodings                            0.5.1
websocket-client                        1.8.0
wikipedia                               1.4.0
wrapt                                   1.17.0
wsproto                                 1.2.0
xlrd                                    2.0.1
xxhash                                  3.5.0
yarl                                    1.17.2

**Comment by kvochko** [comment]
@scofano you should be able to install the requirements now

**Comment by rookiemann** [comment]
I can't seem to find a requirements.txt file to this step:

```
cd custom_nodes/ComfyUI-LTXVideo && pip install -r requirements.txt
```

**Comment by scofano** [comment]
@kvochko Thanks. It worked.
