### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

### ISSUE THREAD

**Issue by bagelbig** [Lightricks/ComfyUI-LTXVideo#41]
Using the img2img workflow downloaded from here, no changes, got the error message:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

I am running on a system with:
1xGPU (20GB VRAM)
2xCPU 

I could find no way to tell it to specifically stick in GPUs.
It did not look like it ran out of VRAM.

Any suggestions?

**Comment by herocoming777** [comment]
same error.

**Comment by bitsentinel-cell** [comment]
same

**Comment by bagelbig** [comment]
I have unexpectedly seemed to work around this problem.  On the same system, I did the following:
1) Remove the env for ComfyUI.
2) Recreate a new env for ComfyUI.
3) Install the latest version of ComfyUI.
4) Load the workflow, and only install missing nodes.

It now launches and runs as expected.

It is possible there was something amiss in one of the other custom nodes installed, or in the version (or installation thereof) of ComfyUI itself.

It's a bit of a bother, but I recommend trying to setup a whole new ComfyUI environment and hope for the best!

(Note, this was done on WSL2).

**Comment by bitsentinel-cell** [comment]
> I have unexpectedly seemed to work around this problem. On the same system, I did the following:
> 
> 1. Remove the env for ComfyUI.
> 2. Recreate a new env for ComfyUI.
> 3. Install the latest version of ComfyUI.
> 4. Load the workflow, and only install missing nodes.
> 
> It now launches and runs as expected.
> 
> It is possible there was something amiss in one of the other custom nodes installed, or in the version (or installation thereof) of ComfyUI itself.
> 
> It's a bit of a bother, but I recommend trying to setup a whole new ComfyUI environment and hope for the best!
> 
> (Note, this was done on WSL2).

thank you it was about the a simple update
