### ISSUE TITLE
Any solution besides downgrading python?  module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### ISSUE THREAD

**Issue by Pedroman1** [Lightricks/ComfyUI-LTXVideo#47]
When installing requirements for portable comfy this is error I get from googling I guess can be fixed by python 3.12 ->python 3.11. Is there an easier way to do this than a brand new install of portable or any chance this will get pactched soon  or do I just need to bite the bullet here. Sorry if has been asked I didn't find when looking. 

error message:
     File "C:\AI\01_ComfyUI\python_embeded\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\AI\01_ComfyUI\python_embeded\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\AI\01_ComfyUI\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

**Comment by fazeaction** [comment]
If you have python 3.12 run `pip install --upgrade setuptools` that worked for me. I'm not using a portable version so backup everything before that command. 🙏

**Comment by Pedroman1** [comment]
Thank you that got me 99% of the way there. For anyone else command line impaired like me here is the exact strings that worked for me for portable comfy install:

1) Open a command prompt from within your **python_embedded directory**
   python -m pip install --upgrade setuptools

2) After this from same command prompt within same directory (obviously changing to your exact folder):
python.exe -m pip install -r C:\AI\01_ComfyUI\ComfyUI\custom_nodes\ComfyUI-LTXVideo\requirements.txt


Thanks again
