### ISSUE TITLE
missing the class_type property

### ISSUE THREAD

**Issue by yakhyo** [Lightricks/ComfyUI-LTXVideo#52]
Cannot execute because a node is missing the class_type property.: Node ID '#106'

I am getting above errors when I run it. 

![image](https://github.com/user-attachments/assets/3cdf9c57-76f1-40d1-9acb-0a914c5306fa)

Below is the message when I click `Queue`. 

![image](https://github.com/user-attachments/assets/279d895f-37b4-4c92-8916-e80a0568bf34)

**Comment by botslop** [comment]
Do you have video helper suite installed?
https://github.com/kosinkadink/ComfyUI-VideoHelperSuite

**Comment by yakhyo** [comment]
You're right. It's fixed now. Thank you @botslop .
