### ISSUE TITLE
EXTREMLY FRUSTRATED WITH THIS MISSING NODES ISSUE which i have no solutions of anywhere

### ISSUE THREAD

**Issue by fusillustrator** [Lightricks/ComfyUI-LTXVideo#71]
![Screenshot 2024-12-17 155450](https://github.com/user-attachments/assets/b52ea1ed-b643-4e59-af2c-dd96a8cee1ab)
![Screenshot 2024-12-17 155440](https://github.com/user-attachments/assets/63f14a2c-d94f-439a-9ba8-98a5bd1bc2dc)

**Comment by michaellightricks** [comment]
can you attach the log?

**Comment by Hardtsonfire** [comment]
I have the exact same problem :(
Running ComfyUI through Google colab using my Google drive as install dir. 
![image](https://github.com/user-attachments/assets/56d1a35b-c459-4109-b7f4-4e3a5d9a62e9)
[comfyui.log](https://github.com/user-attachments/files/18167306/comfyui.log)


I'm sorry for the noob question, but where do I find the logs?
I've attached comfyui.txt from the main comfyui folder, that looks like a log.

**Comment by michaellightricks** [comment]
seems that you didn't install the nodes properly, did you install form Comfy Manager? if you installed manually, did you run pip install -r requirements.txt?

**Comment by Hardtsonfire** [comment]
Hi Michael - thanks for getting back to me/us so quickly.

According to this:
https://github.com/Lightricks/ComfyUI-LTXVideo/issues/3
The workflows are broken.

Now my situation is this: I'm trying to figure out where to put "t5xxl_fp16.safetensors", as the workflow cannot find it, and does not specify where it's looking for it.
![image](https://github.com/user-attachments/assets/a918b7d7-f520-4c70-9f7f-b0aa49c34f54)

**Comment by Hardtsonfire** [comment]
I actually don't remember how I installed the nodes, but the manager is installed.

**Comment by adydeejay** [comment]
> Now my situation is this: I'm trying to figure out where to put "t5xxl_fp16.safetensors", as the workflow cannot find it ...

@Hardtsonfire According to ConfyUI WIKI manual you need to download and place the clip file here:
...\ComfyUI_windows_portable\ComfyUI\models\text_encoders\

I personally have it here and it's very accessible by the Load Clip node:
...\ComfyUI_windows_portable\ComfyUI\models\clip\Stable-Cascade\

More info here:
https://comfyui-wiki.com/en/tutorial/advanced/ltx-video-workflow-step-by-step-guide

**Comment by Hardtsonfire** [comment]
Thanks, appreciate it!
I did put the model in that folder. I think the last problem was related to the Google colab, since it didn't detect it before I disconnected+reconnected my Google drive. Haven't had time to play with it, but I got it working. I hope this helps the original thread creator.

**Comment by XuWeinan123** [comment]
Same problem happened to me, either in my mac or pc.
I already run `pip install -r requirements.txt `
but comfyui still tips "ModuleNotFoundError: No module named 'ltx_video'", and I can't load the LTX nodes
[comfyui_8000.log](https://github.com/user-attachments/files/18173928/comfyui_8000.log)

Also, I trying to import ltx_video in a regular python file, it works.
<img width="214" alt="image" src="https://github.com/user-attachments/assets/d44de372-715e-459a-8e07-3f921c86ac54" />

**Comment by XuWeinan123** [comment]
> Same problem happened to me, either in my mac or pc. I already run `pip install -r requirements.txt ` but comfyui still tips "ModuleNotFoundError: No module named 'ltx_video'", and I can't load the LTX nodes [comfyui_8000.log](https://github.com/user-attachments/files/18173928/comfyui_8000.log)
> 
> Also, I trying to import ltx_video in a regular python file, it works. <img alt="image" width="214" src="https://private-user-images.githubusercontent.com/14000217/396735007-d44de372-715e-459a-8e07-3f921c86ac54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTgwNjQsIm5iZiI6MTczNDQ5Nzc2NCwicGF0aCI6Ii8xNDAwMDIxNy8zOTY3MzUwMDctZDQ0ZGUzNzItNzE1ZS00NTlhLThlMDctM2Y5MjFjODZhYzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA0NTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMzYwZjFiNjM1YThmYmI2Njg2NzA3YjljZmIwZDRjOGYzNzA2OTU1M2ZkZjg3MmVmMWNhNDBiMTAzYjVkOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SKgbqOuWh8Q8pORa75SP3o5Uva-sm-xMHEn-esBFK4A">

Never mind, I forget to active venv enviroment first...

cd ComfyUI folder in Document(my computer is mac)
then run `source .venv/bin/activate`
then `cd custom_nodes/ComfyUI-LTXVideo/`
then run `pip3 install -r requirements.txt`

**Comment by awsynap** [comment]
> > Same problem happened to me, either in my mac or pc. I already run `pip install -r requirements.txt ` but comfyui still tips "ModuleNotFoundError: No module named 'ltx_video'", and I can't load the LTX nodes [comfyui_8000.log](https://github.com/user-attachments/files/18173928/comfyui_8000.log)
> > Also, I trying to import ltx_video in a regular python file, it works. <img alt="image" width="214" src="https://private-user-images.githubusercontent.com/14000217/396735007-d44de372-715e-459a-8e07-3f921c86ac54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTgwNjQsIm5iZiI6MTczNDQ5Nzc2NCwicGF0aCI6Ii8xNDAwMDIxNy8zOTY3MzUwMDctZDQ0ZGUzNzItNzE1ZS00NTlhLThlMDctM2Y5MjFjODZhYzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDA0NTYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMzYwZjFiNjM1YThmYmI2Njg2NzA3YjljZmIwZDRjOGYzNzA2OTU1M2ZkZjg3MmVmMWNhNDBiMTAzYjVkOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SKgbqOuWh8Q8pORa75SP3o5Uva-sm-xMHEn-esBFK4A">
> 
> Never mind, I forget to active venv enviroment first...
> 
> cd ComfyUI folder in Document(my computer is mac) then run `source .venv/bin/activate` then `cd custom_nodes/ComfyUI-LTXVideo/` then run `pip3 install -r requirements.txt`

I'm running on collab.  I had the same issue so I went into terminal and went into custom_nodes/ComfyUI-LTXVideo/` then ran `pip3 install -r requirements.txt as you suggested.

When I launch ComfyUI again it doesn't give me the can't find ComfyUI-LTXV error but now i'm getting this error.  

  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-LTXVideo/loader_node.py", line 15, in <module>
    from .model import LTXVModel, LTXVModelConfig, LTXVTransformer3D
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-LTXVideo/model.py", line 31, in <module>
    class LTXVSampling(torch.nn.Module, comfy.model_sampling.CONST):
AttributeError: module 'comfy.model_sampling' has no attribute 'CONST'

Is anyone having a similar issue?  I've checked to make ComfyUI and ComfyUi Manager are up to date.

**Comment by fusillustrator** [comment]
> can you attach the log?

[comfylog.txt](https://github.com/user-attachments/files/18197018/comfylog.txt)
here is the log file

**Comment by fengchuanyunxiao** [comment]
我也碰到类似的问题了。哪位能够帮忙给出可行的办法吗？
![1734624606521](https://github.com/user-attachments/assets/801368d9-97c0-40ff-bf0a-1b476e743632)

**Comment by michaellightricks** [comment]
> > can you attach the log?
> 
> [comfylog.txt](https://github.com/user-attachments/files/18197018/comfylog.txt) here is the log file

seems that it can't install ltx-video package, try to add --user when you run pip install

**Comment by BobRandomNumber** [comment]
i have this issue also, tried the --user flag, also tried this in pyvenv.cfg include-system-site-packages = true, tried as administrator also
but "ltx-video@git+https://github.com/Lightricks/LTX-Video@ltx-video-0.9.1" fails

**Comment by natie20210522** [comment]
![bug01](https://github.com/user-attachments/assets/8896d15d-1656-4b20-bc23-3a199b593159)
![bug02](https://github.com/user-attachments/assets/64d3f752-6e2e-4b47-b240-6808662a068f)
![bug03](https://github.com/user-attachments/assets/ab18eded-b2f8-48b3-a420-73146e73c0bb)
I encountered the same error and the environment depends on reinstallation. All models were installed in the specified location, including PixArt-XL-2-1024-MS. I checked the positions of the large models ltx-video-2b-v0.9.safensors and ltx-video-2b-v0.91.safetensors using the old workflow, but still received a prompt stating that they are indeed correct
LTXVShiftSigmas
LTXVApplySTG
STGGuider
LTXVModelConfigurator
LTXVLoader

**Comment by natie20210522** [comment]
![bug01](https://github.com/user-attachments/assets/5178d34d-ae25-4b50-a135-817ec28e4c1f)
![bug02](https://github.com/user-attachments/assets/707408a4-8685-4306-9889-af59c7cbb539)
![bug03](https://github.com/user-attachments/assets/0e7d25a6-3241-4d7d-be0e-4d3f81443aed)
I encountered the same error and the environment depends on reinstallation. All models were installed in the specified location, including PixArt-XL-2-1024-MS. I checked the positions of the large models ltx-video-2b-v0.9.safensors and ltx-video-2b-v0.91.safetensors using the old workflow, but the 0.91 workflow still prompts an error
LTXVShiftSigmas
LTXVApplySTG
STGGuider
LTXVModelConfigurator
LTXVLoader

**Comment by fusillustrator** [comment]
> > > can you attach the log?
> > 
> > 
> > [comfylog.txt](https://github.com/user-attachments/files/18197018/comfylog.txt) here is the log file
> 
> seems that it can't install ltx-video package, try to add --user when you run pip install

huh I dont understand

**Comment by 4lt3r3go** [comment]
![image](https://github.com/user-attachments/assets/3e354667-a1bd-4eb3-80f5-974e31f6a670)


same errors here 🤔

**Comment by BobRandomNumber** [comment]
this worked for me to get the ltx-video requirement installed and the node pack now works in comfyui
```py -m pip install https://github.com/Lightricks/LTX-Video/archive/refs/tags/ltx-video-0.9.1.zip```

**Comment by 4lt3r3go** [comment]
i solved in comfy portable by doing:

`C:\Comfy2\python_embeded\python.exe -m pip install -r C:\Comfy2\ComfyUI\custom_nodes\ComfyUI-LTXVideo\requirements.txt`

if you want to try change path accordingly to your correct comfy portable path

**Comment by fusillustrator** [comment]
> i solved in comfy portable by doing this in CMD:
> 
> `C:\Comfy2\python_embeded\python.exe -m pip install -r C:\Comfy2\ComfyUI\custom_nodes\ComfyUI-LTXVideo\requirements.txt`
> 
> if you want to try change path accordingly to your correct comfy portable path

in which folder do I install?

**Comment by 4lt3r3go** [comment]
> in which folder do I install?
 i installed manually. custom nodes git clone repo

**Comment by ynwtray** [comment]
> 这对我来说很有用，可以安装 ltx-video 要求，并且节点包现在可以在 comfyui 中运行 `py -m pip install https://github.com/Lightricks/LTX-Video/archive/refs/tags/ltx-video-0.9.1.zip`
This method is effective for me

**Comment by fusillustrator** [comment]
> > This is very useful for me, you can install ltx-video requirements, and the node package can now run in comfyui `py -m pip install https://github.com/Lightricks/LTX-Video/archive/refs/tags/ltx-video-0.9.1.zip`
> > This method is effective for me

which folder? can you breakdwon the steps for me?

**Comment by ynwtray** [comment]
> py -m pip install https://github.com/Lightricks/LTX-Video/archive/refs/tags/ltx-video-0.9.1.zip

custom_nodes\ComfyUI-LTXVideo

**Comment by ynwtray** [comment]
> py -m pip install https://github.com/Lightricks/LTX-Video/archive/refs/tags/ltx-video-0.9.1.zip

You also need to upgrade onnxruntime-gpu>=1.19.0 and restart comfyui

**Comment by fusillustrator** [comment]
> > py -m pip install https://github.com/Lightricks/LTX-Video/archive/refs/tags/ltx-video-0.9.1.zip
> 
> You also need to upgrade onnxruntime-gpu>=1.19.0 and restart comfyui

I am so lost , If you have time can you breakdown the steps for me ? Itsnot working maybe because I amnot doing correctly

**Comment by fusillustrator** [comment]
Solved this by inputting this : 
python -m pip install https://github.com/Lightricks/LTX-Video/archive/refs/tags/ltx-video-0.9.1.zip
on comfyui's python folder , there was an error that stops me from installing i sorted that by turning of the git security
using:
set GIT_CLONE_PROTECTION_ACTIVE=false

and then finally installed .

**Comment by Campzilla** [comment]
I was facing this issue with missing LTXV nodes in ComfyUI, even though I had installed the repository multiple times in comfy manager (automatic mode) and manually with cmd. The nodes didn't show up in the missing nodes list on comfyui manager, and the repo seemed to not install correctly.

After some investigation, I went to the Custom Nodes Manager, searched for "ltx" and noticed that the nodes were not actually installed, despite the installation attempts. Once I manually installed them via the Custom Nodes Manager, everything started working fine.

This fixed the issue for me.

**Comment by sora-1337** [comment]
if nothing works, update your git on your pc.
theres a git version that has a rollbacked LFS handling fix that causes issues when its trying to pull the additional big LFS data from the repo.

**Comment by VoVchicbest** [comment]
So. My problem is much deeper. If nothing else has helped you, this method will work, but you won't be able to update Comfy. I made a separate folder with Comfy for the LTX STG desktop only. What is the problem. I can't install ltx-video-0.9.1 - I tried 20 ways to install it and always installs version 0.1.2. So, I create a separate folder with Comfy, install the manager, install all the necessary nodes through it. I close and block it so that Comfy cannot access the Internet. In the python_embeded\Lib\site-packages folder, delete 2 folders named ltx* and copy the ltx_video folder from https://github.com/Lightricks/LTX-Video/archive/refs/tags/ltx-video-0.9.1.zip (only ltx_video - not the entire LTX-Video-ltx-video-0.9.1 folder) After that, everything works. As soon as you open access to the internet, Comfy will see the version error, fix yours to 0.1.2 and everything will stop working. If anyone has another option for me, please let me know.

**Comment by TH-Boss** [comment]
"zip"  helps a lot!!!!! Finally fixed this issue

**Comment by tridhe** [comment]
Install [ComfyUI-LTXTricks] from your 'Custom Node Manager' and this error will be resolved.


<img width="1120" alt="Image" src="https://github.com/user-attachments/assets/c3c2cd44-cb94-4c7f-9ec7-6c5ba28cd1a7" />

**Comment by Tapyon** [comment]
Im having same issue here , after getting everything right , but now thos specific nodes are not install !!
try all the tips from above but nothing ! 
 and i try to unistall from the Manager COMFYUI LTX VIDEO NODES and its like still there, can install them now ... but folder is empty! 
something new about this ?

**Comment by Tapyon** [comment]
Traceback (most recent call last):
  File "C:\Users\franc\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2110, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\franc\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\__init__.py", line 1, in <module>
    from .loader_node import LTXVLoader  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\franc\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo\loader_node.py", line 10, in <module>
    from ltx_video.models.autoencoders.causal_video_autoencoder import (
ModuleNotFoundError: No module named 'ltx_video'

**Comment by mrrajeshhamal** [comment]
Just install `ComfyUI-LTXVideo` from Custom Node Manager.

**Comment by hawe80** [comment]
I have the same problem in ComfyUI_windows_portable, what i have done so far: 
* installed `ComfyUI-LTXVideo`  from Custom Node Manager
* updated git
* updated ComfyUI via update_comfyui.bat
* tried to update from ComfyUI Manager
* tried installing : python_embeded/python -m pip install https://github.com/Lightricks/LTX-Video/archive/refs/tags/ltx-video-0.9.1.zip like mentioned earlier here
* 
Nothing worked so far
![Image](https://github.com/user-attachments/assets/431d23be-b77b-46bc-9bc1-51e9e16295c9)

![Image](https://github.com/user-attachments/assets/4e334c68-9b65-49c2-ae47-0051b5179789)

**Comment by mineov** [comment]
I have a question why to use this Workflow with missing nodes.
![Image](https://github.com/user-attachments/assets/8cf58821-20ca-401c-8c71-2e57859819e1)

Cause i had seen there is a Workflow in the templates for LTX-Video which has no errors.

![Image](https://github.com/user-attachments/assets/cc911fcb-3414-43b8-a5da-6301e2797fa0)
![Image](https://github.com/user-attachments/assets/52b8a95f-d85f-4950-8a46-3f7f5bcccc89)

DO THEY BOTH HAVE SOME DIFFERENCE LIKE GENERATION QUALITY etc?
