### ISSUE TITLE
how to fix this error model 0.9.1

### ISSUE THREAD

**Issue by rafiislambd** [Lightricks/ComfyUI-LTXVideo#78]
how to fix this error model 0.9.1
![2](https://github.com/user-attachments/assets/b4436fc4-90b6-4fa3-8702-4b032c6d5d80)
![fff](https://github.com/user-attachments/assets/d59d8620-ea3a-4552-a78f-67eede9e3dff)

**Comment by kvochko** [comment]
For now you have to use the workflows provided in this repository - comfy core doesn’t support the new VAE yet.

https://github.com/Lightricks/ComfyUI-LTXVideo/tree/master/assets

**Comment by 4lt3r3go** [comment]
![image](https://github.com/user-attachments/assets/e6d3f31c-3857-4577-ad67-646c3841e5d6)

im using those and got this 😯🤷
comfy is updated

**Comment by kvochko** [comment]
ComfyUI has implemented support for the new VAE now, the workflow should work after updating comfy.
